apiVersion: v1
kind: Service
metadata:
  name: layer4-lb-service
spec:
  selector:
    app: layer4-lb
  type: LoadBalancer # Or NodePort / ClusterIP
  ports:
    - name: app-traffic
      protocol: TCP
      port: 80 # External port
      targetPort: 8080 # Internal LB port
    - name: admin-traffic
      protocol: TCP
      port: 8082 # External port
      targetPort: 8082 # Internal LB port
    # - name: cluster-gossip
    #   protocol: UDP
    #   port: 9090
    #   targetPort: 9090
