apiVersion: v1
kind: Service
metadata:
  name: layer4-lb-service
spec:
  selector:
    app: layer4-lb
  type: LoadBalancer # Or NodePort / ClusterIP
  ports:
    - name: redis-traffic
      protocol: TCP
      port: 6379 # External port
      targetPort: 6379 # Internal LB port
    # - name: cluster-gossip
    #   protocol: UDP
    #   port: 9090
    #   targetPort: 9090
